name: ArcadesEconomy
main: me.scruffyboy13.ArcadesEconomy.ArcadesEconomyMain
version: 2.3
api-version: 1.13
author: scruffyboy13
depend: [Vault]
load: STARTUP

commands:
  arcadescoin:
    aliases: [arcadesc]
  arcadesbalance:
    aliases: [arcadesbal]
  arcadesbalancetop:
    aliases: [arcadesbaltop]
  arcadespay:
    aliases: []

permissions:
  arcadeseconomy.command.balance:
    default: true
  arcadeseconomy.command.balancetop:
    default: true
  arcadeseconomy.command.help:
    default: true
  arcadeseconomy.command.pay:
    default: op
  arcadeseconomy.command.give:
    default: op
  arcadeseconomy.command.take:
    default: op
  arcadeseconomy.command.set:
    default: op
  arcadeseconomy.command.reload:
    default: op